### ISSUE TITLE
还会出新的功能吗

### ISSUE THREAD

**Issue by cq10086123** [iHunterDev/JianYingProBatchKeyframe#1]
如果   图片 SR字幕  SR字幕 MP3 一键合成草稿

**Comment by iHunterDev** [comment]
会，目前正在开发客户端，你说的这个功能目前没有计划要做。

客户端介绍：https://keyframeai.top/zh_CN/copilot
开源地址：https://github.com/iHunterDev/JianYingProBatchKeyframeCopilot
