### ISSUE TITLE
关键帧目前最多只能10秒，请增加功能自定义关键帧时间

### ISSUE THREAD

**Issue by small-tk** [iHunterDev/JianYingProBatchKeyframe#5]
关键帧目前最多只能10秒，请增加功能自定义关键帧时间

**Comment by iHunterDev** [comment]
不明白你想要的功能，你想要达成什么样的效果，最好提供一下草稿文件和说明视频以方便理解需求。

**Comment by small-tk** [comment]
是这样的大佬，我创作内容有很多图片时长都在30秒-1分钟，希望关键帧能够覆盖整个时长，目前的程序只能有10秒关键帧，你可以放一些30秒以上的图片试一下

**Comment by iHunterDev** [comment]
> 是这样的大佬，我创作内容有很多图片时长都在30秒-1分钟，希望关键帧能够覆盖整个时长，目前的程序只能有10秒关键帧，你可以放一些30秒以上的图片试一下

我已找到问题所在，目前正在修复这个问题。

**Comment by iHunterDev** [comment]
> > 是这样的大佬，我创作内容有很多图片时长都在30秒-1分钟，希望关键帧能够覆盖整个时长，目前的程序只能有10秒关键帧，你可以放一些30秒以上的图片试一下
> 
> 我已找到问题所在，目前正在修复这个问题。

目前该问题已经得到了修复，并且已部署上线。
